<?php
require __DIR__ . '/includes/db.php';
require __DIR__ . '/includes/auth.php';
require __DIR__ . '/includes/subscription.php';

$pageTitle = 'Terms of Use';
require __DIR__ . '/includes/header.php';
?>

<div class="row justify-content-center">
    <div class="col-lg-8">
        <div class="card card-custom">
            <div class="card-body p-4">
                <h4 class="fw-bold mb-1">Terms of Use</h4>
                <p class="text-muted small mb-4">Last updated: March 2026</p>

                <h6 class="fw-bold mt-4">1. Acceptance of Terms</h6>
                <p class="text-muted small">By accessing or using Argonar Construction ("the Service") at argonar.co, you agree to be bound by these Terms of Use. If you do not agree, do not use the Service.</p>

                <h6 class="fw-bold mt-4">2. Service Description</h6>
                <p class="text-muted small">Argonar Construction provides online construction estimation and document generation tools, including BOQ Generator, Rebar Cutting List, Structural Estimate, Architectural Estimate, Document Generator, and Excel Templates. All tools are provided as-is for estimation purposes only.</p>

                <h6 class="fw-bold mt-4">3. User Accounts</h6>
                <p class="text-muted small">You are responsible for maintaining the confidentiality of your account credentials. You must provide accurate information during registration. One account per person. Sharing accounts is not permitted.</p>

                <h6 class="fw-bold mt-4">4. Subscriptions & Payments</h6>
                <p class="text-muted small">Access to tools requires a paid subscription (24-Hour Pass or Monthly Plan). Payments are processed securely by PayRex. Subscription access begins immediately upon successful payment and expires after the purchased duration (24 hours or 30 days).</p>

                <h6 class="fw-bold mt-4">5. No Refund Policy</h6>
                <p class="text-muted small"><strong>All sales are final. No refunds will be issued once a subscription has been activated.</strong> Since access is granted immediately upon payment, we cannot offer refunds for unused time. By purchasing a subscription, you acknowledge and accept this no-refund policy. If you experience technical issues preventing access, contact us and we will work to resolve the issue.</p>

                <h6 class="fw-bold mt-4">6. Auto-Renewal</h6>
                <p class="text-muted small">If you enable auto-renewal, you will receive an in-app notification with a payment link before your subscription expires. Auto-renewal does not automatically charge you. You must complete the payment manually. You can disable auto-renewal at any time from your subscription settings.</p>

                <h6 class="fw-bold mt-4">7. Acceptable Use</h6>
                <p class="text-muted small">You agree not to: (a) use the Service for any unlawful purpose; (b) attempt to gain unauthorized access to the Service or its systems; (c) use automated tools to scrape or extract data from the Service; (d) share your account with others or resell access.</p>

                <h6 class="fw-bold mt-4">8. Disclaimer of Warranties</h6>
                <p class="text-muted small">The Service provides construction estimates and documents for reference purposes only. All calculations, quantities, and costs generated by the tools are estimates and should be verified by a licensed professional engineer or architect before use in actual construction projects. Argonar Construction is not liable for any errors, inaccuracies, or losses resulting from the use of generated estimates or documents.</p>

                <h6 class="fw-bold mt-4">9. Limitation of Liability</h6>
                <p class="text-muted small">To the maximum extent permitted by law, Argonar Construction shall not be liable for any indirect, incidental, special, or consequential damages arising from the use or inability to use the Service.</p>

                <h6 class="fw-bold mt-4">10. Changes to Terms</h6>
                <p class="text-muted small">We may update these terms at any time. Continued use of the Service after changes constitutes acceptance of the updated terms.</p>

                <h6 class="fw-bold mt-4">11. Contact</h6>
                <p class="text-muted small">For questions about these terms, contact us at <a href="mailto:support@argonar.co">support@argonar.co</a>.</p>
            </div>
        </div>
    </div>
</div>

<?php require __DIR__ . '/includes/footer.php'; ?>
